import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../../styles/Competition.module.css";
import axios from "axios";
import Link from "next/link";

import Standing from "../../components/Standing";
import Matches from "../../components/Matches";

const Index = () => {
  let location;
  if (typeof window !== "undefined") {
    // browser code
    location = window.location.href;
  }

  console.log(location);
  const id = location.slice(37);
  // let id = JSON.parse(query.id);
  // const id = localStorage.getItem("id");
  // localStorage.clear();
  const [data, setData] = useState([]);
  const [matchday, setMatcday] = useState();

  useEffect(() => {
    const fetchData = () => {
      axios({
        method: "get",
        url: `http://api.football-data.org/v2/competitions/${id}`,
        headers: {
          "Content-Type": "application/json; charset=UTF-8",

          "X-Auth-Token": "84019147ef2a45a78afe6dcf4919a779",
        },
      })
        .then((response) => {
          // console.log(response.data.competitions);
          console.log(response.data.currentSeason);
          setMatcday(response.data.currentSeason.currentMatchday);

          setData(response.data);
        })
        .catch((err) => {
          // console.log(err.response);
        });
    };
    fetchData();
  });
  //   console.log(data);

  return (
    <div>
      <Head>
        <title>Competiton</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.headerBg}>
          <div className="container">
            <div className={styles.logo}>
              <Image
                src="https://sportify-git-master.itope84.vercel.app/img/logo.efdde25b.png"
                alt="sportify_logo"
                width={200}
                height={200}
              />
            </div>
          </div>
        </div>
      </header>

      <main className="container">
        <div className={`card ${styles.card}`}>
          <div className="card-body">
            <div className="py-2 mb-3">
              <Link href="/">
                <span
                  style={{
                    cursor: "pointer",
                    color: "#292a2a",
                    boxShadow: "inset 0 -2px 0 0 #347ab8",
                    padding: "5px",
                  }}
                >
                  All Competition
                </span>
              </Link>
              <span className="mx-2">/</span>
              <span className="text-muted">{data.name}</span>
            </div>
            <h4 className="text-primary">{data.name}</h4>
            {/* <div className="row tabs">
              <div className="col-6 d-flex">
                <div className="tab">
                  <span className="header">Standings</span>
                </div>
              </div>

              <div className="col-6 d-flex">
                <div className="tab">
                  <span className="header">MATCHES</span>
                </div>
              </div>
            </div>

            <div className="tab-body-holder">
              <transition name="fade-right"></transition>
            </div> */}

            <ul
              className={`nav ${styles.tabs} row  nav-tabs`}
              id="myTab"
              role="tablist"
            >
              <li className="nav-item col-6 d-flex" role="presentation">
                <a
                  className={`nav-link ${styles.tab} active`}
                  id="home-tab"
                  data-bs-toggle="tab"
                  href="#home"
                  role="tab"
                  aria-controls="home"
                  aria-selected="true"
                >
                  Standing
                </a>
              </li>
              <li className="nav-item col-6 d-flex" role="presentation">
                <a
                  className={`nav-link ${styles.tab}`}
                  id="profile-tab"
                  data-bs-toggle="tab"
                  href="#profile"
                  role="tab"
                  aria-controls="profile"
                  aria-selected="false"
                >
                  Matches
                </a>
              </li>
            </ul>
            <div className="tab-content" id="myTabContent">
              <div
                className="tab-pane fade show active"
                id="home"
                role="tabpanel"
                aria-labelledby="home-tab"
              >
                <Standing id={id} />
              </div>
              <div
                className="tab-pane fade"
                id="profile"
                role="tabpanel"
                aria-labelledby="profile-tab"
              >
                <Matches matchday={matchday} id={id} />
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Onuiteshi/fresible"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className="">
            Developed By <strong>Onuiteshi Emmanuel</strong>{" "}
          </span>
        </a>
        <p>Credits : Football data API</p>
      </footer>
    </div>
  );
};

export default Index;
