import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Loader from "react-loader-spinner";
import Link from "next/link";
import axios from "axios";

export default function Home() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const sapa = [{ phone: "iphone" }, { debts: "loans" }, { bills: "Repairs" }];

  useEffect(() => {
    const fetchData = () => {
      axios({
        method: "get",
        url: `http://api.football-data.org/v2/competitions`,
        headers: {
          "Content-Type": "application/json; charset=UTF-8",

          "X-Auth-Token": "84019147ef2a45a78afe6dcf4919a779",
        },
      })
        .then((response) => {
          // console.log(response.data.competitions);
          const newData = response.data.competitions.filter((item) => {
            if (
              item.id === 2016 ||
              item.id === 2021 ||
              item.id === 2001 ||
              item.id === 2018 ||
              item.id === 2015 ||
              item.id === 2002 ||
              item.id === 2019 ||
              item.id === 2003 ||
              item.id === 2017 ||
              item.id === 2014
            ) {
              return item;
            }
          });
          // console.log(newData);
          setData(newData);
        })
        .catch((err) => {
          // console.log(err.response);
        });
    };
    fetchData();
  }, []);
  console.log(data);

  return (
    <div>
      <Head>
        <title>Sportify</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.headerBg}>
          <div className="container">
            <div className={styles.logo}>
              <Image
                src="https://sportify-git-master.itope84.vercel.app/img/logo.efdde25b.png"
                alt="sportify_logo"
                width={200}
                height={200}
              />
            </div>
          </div>
        </div>
      </header>

      <main className="container">
        <div className={`card ${styles.card}`}>
          <div className="card-body">
            <h4>All Competitions</h4>
            <div className="row">
              {data.length ? (
                data.map((item) => (
                  <Link
                    href={{
                      pathname: "/competition",
                      query: { id: JSON.stringify(item.id) },
                    }}
                    key={item.id}
                    passHref
                  >
                    <div className="col-sm-6 mb-4">
                      <div
                        className={`px-4 py-4  rounded-sm ${styles.competitions}`}
                      >
                        <div className={styles.emblem}>
                          <Image
                            src={
                              item.code === "PL"
                                ? "https://cdn.freelogovectors.net/wp-content/uploads/2020/08/epl-premierleague-logo.png"
                                : item.code === "FL1"
                                ? "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ligue1.svg/1200px-Ligue1.svg.png"
                                : item.code === "BL1"
                                ? "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Bundesliga_logo_%282017%29.svg/1200px-Bundesliga_logo_%282017%29.svg.png"
                                : item.code === "DED"
                                ? "https://www.dutchnews.nl/wpcms/wp-content/uploads/2015/02/eredivisie-logo-football.jpg"
                                : item.code === "PD"
                                ? "https://www.egypttoday.com/siteimages/Larg/33237.jpg"
                                : item.code === "ELC"
                                ? "https://www.pngitem.com/pimgs/m/490-4901942_sky-bet-championship-logo-png-png-download-english.png"
                                : item.code === "PPL"
                                ? "https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/14.png"
                                : item.emblemUrl
                            }
                            alt="emblem"
                            width={80}
                            height={80}
                          />
                        </div>
                        <div style={{ flex: "1" }}>
                          <h5 className="mb-1">{item.name}</h5>
                          <p>{item.area.name}</p>
                        </div>
                      </div>
                    </div>
                  </Link>
                ))
              ) : (
                <Loader
                  type="Puff"
                  color="#00BFFF"
                  style={{ textAlign: "center" }}
                  height={300}
                  width={300}
                  // timeout={4000} //3 secs
                />
              )}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Onuiteshi/fresible"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className="">
            Developed By <strong>Onuiteshi Emmanuel</strong>{" "}
          </span>
        </a>
        <p>Credits : Football data API</p>
      </footer>
    </div>
  );
}
